/* PittCo Fishing — unified lake hub extras for Lake Directory profiles. */
(function(){
'use strict';
let hubToken=0;
const $id=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const AUTH={
 'ok-sardis':{label:'USACE Tulsa District + ODWC + OWRB',ops:'https://www.swt-wc.usace.army.mil/SARD.lakepage.html',fish:'https://www.wildlifedepartment.com/fishing/wheretofish/southeast/sardis-lake',note:'USACE water operations; ODWC fishing reports/species; OWRB verified bathymetry where available.'},
 'ok-eufaula':{label:'USACE Tulsa District + ODWC + OWRB',ops:'https://www.swt-wc.usace.army.mil/EUFA.lakepage.html',fish:'https://www.wildlifedepartment.com/fishing/wheretofish/southeast/eufaula',note:'USACE water operations; ODWC fishing reports/species; OWRB depth data where verified.'},
 'ok-broken-bow':{label:'USACE Tulsa District + ODWC + OWRB',ops:'https://www.swt-wc.usace.army.mil/BROK.lakepage.html',fish:'https://www.wildlifedepartment.com/fishing/wheretofish/southeast/broken-bow-lake',note:'USACE water operations; ODWC fishing reports/species; seasonal conservation-pool reference.'},
 'ok-tenkiller':{label:'USACE Tulsa District + ODWC + OWRB',ops:'https://www.swt-wc.usace.army.mil/TENK.lakepage.html',fish:'https://www.wildlifedepartment.com/fishing/wheretofish/northeast/tenkiller',note:'USACE water operations; ODWC fishing reports/species; OWRB depth data only when verified.'},
 'ok-grand':{label:'GRDA + ODWC + OWRB',ops:'https://stormops.grda.com/riveroperations',fish:'https://wildlifedepartment.com/fishing/wheretofish/northeast/grand-lake',note:'GRDA river operations provides current Grand Lake headwater level and gross generation; ODWC provides fishing/regulation information.'},
 'ok-hudson':{label:'GRDA + ODWC + OWRB',ops:'https://stormops.grda.com/riveroperations',fish:'https://www.wildlifedepartment.com/fishing/wheretofish/northeast/hudson',note:'GRDA river operations provides current Lake Hudson headwater level and generation; ODWC provides fishing, regulations and public-ramp information.'},
 'ok-mcgee-creek':{label:'Bureau of Reclamation + ODWC + OWRB',ops:'https://data.usbr.gov/visualizations/reservoir-conditions/',fish:'https://www.wildlifedepartment.com/fishing/wheretofish/southeast/mcgee-creek',project:'https://www.usbr.gov/projects/index.php?id=351',note:'Bureau of Reclamation is the federal project authority and publishes reservoir-condition data; ODWC provides fishing information.'}
};
function lakeById(id){try{return Array.isArray(catalog)?catalog.find(x=>x.id===id):null}catch(e){return null}}
function ensureStyles(){if($id('pittcoLakeHubStyles'))return;const s=document.createElement('style');s.id='pittcoLakeHubStyles';s.textContent='.lakeHub{margin:10px 0 3px;border:1px solid #3f3150;background:#09090e;border-radius:14px;padding:11px}.lakeHub h3{font-size:15px;margin:0 0 9px}.hubTitle{display:flex;justify-content:space-between;gap:8px;align-items:center}.hubTitle small{font-size:7px;color:#aaa5b2}.hubGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.hubStat{border:1px solid #302936;background:#0d0d13;border-radius:10px;padding:8px}.hubStat b{display:block;font-size:13px;color:#fff}.hubStat small{display:block;color:#aaa5b2;font-size:7px;margin-top:3px}.hubSection{margin-top:10px}.hubSection>b{font-size:9px;color:#d670ff;text-transform:uppercase;letter-spacing:.05em}.hubSection p{font-size:9px;line-height:1.45;color:#ddd7e1;margin:5px 0 0}.hubLinks{display:grid;grid-template-columns:repeat(2,1fr);gap:6px;margin-top:7px}.hubLinks a{border:1px solid #44314f;background:#101016;color:#fff;border-radius:10px;padding:9px 7px;text-decoration:none;text-align:center;font-size:8px;font-weight:900}.hubLinks a.primary{border-color:#843aa1;background:#1b0c25;color:#e9c5ff}.hubAuthority{border:1px solid #315245;background:#0b1512;border-radius:11px;padding:8px;margin-top:7px}.hubAuthority strong{display:block;color:#83efc2;font-size:9px}.hubAuthority small{display:block;color:#aaa5b2;font-size:7px;line-height:1.4;margin-top:4px}.hubRamps{display:grid;gap:5px;margin-top:6px}.hubRamp{border:1px solid #302936;background:#0d0d13;border-radius:9px;padding:7px 8px}.hubRamp b{display:block;font-size:9px;color:#fff}.hubRamp small{font-size:7px;color:#aaa5b2}.hubGood{color:#83efc2!important}.hubMuted{color:#aaa5b2!important}@media(max-width:370px){.hubGrid,.hubLinks{grid-template-columns:1fr}.hubTitle{align-items:flex-start;flex-direction:column}}';document.head.appendChild(s)}
function stat(label,value,cls=''){return '<div class="hubStat"><b class="'+cls+'">'+esc(value)+'</b><small>'+esc(label)+'</small></div>'}
function weatherCode(c){c=Number(c);if(c===0)return'Sunny';if(c<=3)return'Partly cloudy';if(c<=48)return'Fog';if(c<=67)return'Rain';if(c<=82)return'Showers';if(c>=95)return'Storms';return'Conditions'}
function route(file,id){return '/?route='+encodeURIComponent(file+'?lake='+id)}
function authoritySection(id){const a=AUTH[id];if(!a)return'';let links='<a class="primary" href="'+esc(a.ops)+'" target="_blank" rel="noopener">Official water / operations ↗</a><a href="'+esc(a.fish)+'" target="_blank" rel="noopener">Official fishing report ↗</a>';if(a.project)links+='<a href="'+esc(a.project)+'" target="_blank" rel="noopener">Federal project profile ↗</a>';return '<div class="hubSection"><b>Official lake sources</b><div class="hubAuthority"><strong>'+esc(a.label)+'</strong><small>'+esc(a.note)+'</small></div><div class="hubLinks">'+links+'</div></div>'}
function shell(id,x){const panel=document.querySelector('.panel');if(!panel||!x)return null;let box=$id('lakeHub');if(!box){box=document.createElement('section');box.id='lakeHub';box.className='lakeHub';const privacy=panel.querySelector('.privacy');privacy?panel.insertBefore(box,privacy):panel.appendChild(box)}box.innerHTML='<div class="hubTitle"><h3>Lake Hub</h3><small>Everything tied to '+esc(x.name)+'</small></div><div class="hubSection"><b>Current fishing conditions</b><div class="hubGrid" id="hubWeather"><div class="hubStat"><b>Loading…</b><small>LIVE WEATHER</small></div></div></div>'+authoritySection(id)+'<div class="hubSection"><b>Boat ramps</b><div id="hubRamps"><p class="hubMuted">Loading public ramp locations near this lake…</p></div></div><div class="hubSection"><b>Open lake tools</b><div class="hubLinks"><a class="primary" href="'+route('map.html',id)+'">Map + depth + ramps</a><a href="'+route('weather.html',id)+'">Full forecast</a><a href="/?route=community.html?lake='+encodeURIComponent(id)+'">Lake community</a><a href="/?route=legacy.html%23catches">Catch log</a></div></div>';return box}
async function loadWeather(x,token){const host=$id('hubWeather');if(!host)return;try{const u='https://api.open-meteo.com/v1/forecast?latitude='+encodeURIComponent(x.lat)+'&longitude='+encodeURIComponent(x.lon)+'&current=temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,wind_speed_10m,surface_pressure,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=auto&forecast_days=2';const j=await fetch(u,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});if(token!==hubToken||!document.body.contains(host))return;const c=j.current||{},d=j.daily||{},p=Number(c.surface_pressure)*.02953;host.innerHTML=stat('CONDITION',weatherCode(c.weather_code)+' • '+Math.round(c.temperature_2m)+'°','hubGood')+stat('FEELS LIKE',Math.round(c.apparent_temperature)+'°')+stat('WIND',Math.round(c.wind_speed_10m||0)+' mph')+stat('HUMIDITY',Math.round(c.relative_humidity_2m||0)+'%')+stat('PRESSURE',Number.isFinite(p)?p.toFixed(2)+' inHg':'—')+stat('TODAY',Math.round(d.temperature_2m_max?.[0])+'° / '+Math.round(d.temperature_2m_min?.[0])+'°')+stat('RAIN CHANCE',Math.round(d.precipitation_probability_max?.[0]||0)+'%')+stat('CURRENT PRECIP',Number(c.precipitation||0).toFixed(2)+' in')}catch(e){if(token!==hubToken)return;host.innerHTML=stat('LIVE WEATHER','Temporarily unavailable','hubMuted')}}
async function loadRamps(x,token){const host=$id('hubRamps');if(!host)return;try{const q='[out:json][timeout:18];(nwr["leisure"="slipway"](around:15000,'+Number(x.lat)+','+Number(x.lon)+');nwr["amenity"="boat_ramp"](around:15000,'+Number(x.lat)+','+Number(x.lon)+'););out center tags;';const url='https://overpass-api.de/api/interpreter?data='+encodeURIComponent(q);const j=await fetch(url,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()});if(token!==hubToken||!document.body.contains(host))return;const rows=(j.elements||[]).map(e=>{const t=e.tags||{},name=t.name||t.official_name||'Public boat ramp',access=t.access||t.boat||'',status=access==='no'?'Access tagged closed/restricted':access==='private'?'Private access':access==='customers'?'Customer access':access==='yes'||access==='permissive'?'Public access':'Operational status not published';return{name,status}});const uniq=[];const seen=new Set();for(const r of rows){const k=r.name+'|'+r.status;if(!seen.has(k)){seen.add(k);uniq.push(r)}}const shown=uniq.slice(0,8);if(!shown.length){host.innerHTML='<p class="hubMuted">No public ramp records were returned within 15 km. Open the map for broader nearby coverage.</p>';return}host.innerHTML='<p>'+uniq.length+' mapped ramp '+(uniq.length===1?'record':'records')+' found nearby. Status is only shown when the public map record includes an access tag.</p><div class="hubRamps">'+shown.map(r=>'<div class="hubRamp"><b>'+esc(r.name)+'</b><small>'+esc(r.status)+'</small></div>').join('')+'</div><p class="hubMuted">Ramp locations: OpenStreetMap community data. Verify closures/operational status with the managing agency before travel.</p>'}catch(e){if(token!==hubToken)return;host.innerHTML='<p class="hubMuted">Ramp inventory is temporarily unavailable. The lake map still provides the ramp layer when the public source responds.</p>'}}
async function renderHub(id){const token=++hubToken,x=lakeById(id);if(!x)return;ensureStyles();shell(id,x);loadWeather(x,token);loadRamps(x,token)}
function init(){ensureStyles();if(typeof openLake==='function'){const original=openLake;openLake=function(id){const r=original.apply(this,arguments);setTimeout(()=>renderHub(id),20);return r}}}
init();
})();
